name: 'pre-release'
description: 'Provides automated versioning of your commits using git tags each time your CI/CD workflow runs.'
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  dry-run:
    description: 'Enable dry run mode'
    required: false
    default: 'false'
  prefix:
    description: 'Release prefix'
    required: false
  pre-release:
    description: 'A prerelease'
    required: false
outputs:
  tag:
    description: 'The new version that was created and tagged in the format of <major>.<minor>.<build>[.<pre-release-tag>]'
runs:
  using: 'node12'
  main: 'action-pre-release/index.js'