name: Front

on:
  push:
    branches:
      - !main
    paths:
    - 'front/**/*'

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run tests
        run: |
          yarn install
          yarn test
        working-directory: ./front

