name: Back/Tests

on:
  push:
    branches-ignore:
      - main
      - release*
    tags-ignore:
      - release*
    paths:
      - "back/**/*"

jobs:
  test-back:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Test
        run: go test ./... -cover -v -coverprofile=back-coverage.out
        working-directory: ./back
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: back-coverage-report
          path: back-coverage.out
