name: Back/DockerBuild

on:
  push:
    tags:
    - "release*"

jobs:
  docker-build:
    runs-on: ubuntu-latest    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: back/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.pkg.github.com/intelygenz/github-actions-poc/back:latest
            docker.pkg.github.com/intelygenz/github-actions-poc/back:1.0.0
