name: CreateRelease

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version number'
        required: true
        default: 'false'
      minor:
        description: 'Minor version number'
        required: true
        default: 'true'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
        - uses: peterjgrainger/action-create-branch@v2.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: 'release-${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}'
        