name: FeatPreRelease

on:
  push:
    branches:
      - test/branch
  # workflow_dispatch:
  #   branches:
  #     - test/branch

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release
        uses: ./action-product-version-tags
        with:
          dry-run: true
          current-major: 1
          prefix: "release-"
          pre-release: 'alpha'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
