name: FeatPreRelease

on:
  pull_request:
      branches:
        - feat/semantic-release-basic-approach

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          branch: feat/semantic-release-basic-approach
          branches: |    
            [
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
          extra_plugins: |
            ["@semantic-release/commit-analyzer", {
              "preset": "angular",
              "releaseRules": [
                {"type": "*", "release": "patch"},
              ]
            }]

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}