name: FeatPreRelease

on:
  pull_request:
      branches:
        - feat/*

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v3
        with:
          # A string to determine the format of the version output
          format: "${major}.${minor}-alpha.${increment}"

