name: Fix

on:
  push:
    branches:
      - "release-*"

jobs:
  create-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate a fix
        uses: ./action-product-version-tags
        with:
          prefix: "release-"
          mode: 'fix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        