name: Front/Tests

on:
  push:
    paths:
        - "front/**/*"

jobs:
  test-front:
    if: github.ref != 'main' && !contains(github.ref, 'release-') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run tests
        run: |
          yarn install
          yarn test
        working-directory: ./front

