name: Front/Docker_Build

on:
  push:
    tags:
    - "release*"

jobs:
  docker-build:
    runs-on: ubuntu-latest    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/release-}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: front/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/intelygenz/github-actions-poc/front:${{ steps.get_version.outputs.VERSION }}