name: Front/Docker_Build

on:
  push:
    tags:
    - "release-**"

jobs:
  docker-build:
    runs-on: ubuntu-latest    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          platforms: linux/amd64,linux/arm64
          repository: intelygenz/github-actions-poc
          push: false
          tags: |
            user/app:latest
            user/app:1.0.0