name: Release Helm Charts

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: chrisdickinson/setup-yq@latest
      - name: Show folks how to run YQ
        run:  |
          yq w -i helm/actions-poc/values.yaml '*.image.tag' ${{ steps.get_version.outputs.VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: 'helm'
          charts_repo_url: 'https://intelygenz.github.io/github-actions-poc'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
