name: PreRelease

on:
  workflow_run:
    workflows: ["Back/Tests", "Front/Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate a pre-release
        uses: intelygenz/action-product-version-tags@v0.1.4
        with:
          # TODO: Rename prefix release and pre-release fields to branch-prefix and tag-prefix
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'alpha'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
