name: SemanticPreRelease

on:
  pull_request:
      branches:
        - feat/*

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          # you can set branches for semantic-release above v16.
          branches: |    
            [
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

