name: FRONT

on:
  push:
    paths:
    - 'front/**'

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run tests
        run: |
          yarn install
          yarn test
        working-directory: ./front
  
  docker-build:
    runs-on: ubuntu-latest    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
